### PR TITLE
sysctl settings for slurmctld

### PR DESCRIPTION
**Pull request by jabl**
Based on the recommendations in the slurm high throughput computing
guide.

### CODE REVIEW

**Comment by martbhell** [comment]
We can already set sysctl.d values with a variable. See the system-limits role. Maybe we can skip doing it in this role?

**Comment by jabl** [comment]
Sure, it's doable via the system-limits role. I thought it would be nicer here to keep the role a bit more self-contained and make it clearer why these settings are here, and also by using the ansible builtin sysctl module it doesn't conflict with other sysctl settings which may or may not be set via the global system-limits role.

**Comment by martbhell** [comment]
Fair enough. It is already quite a beast so it would be nice to contain it.

**Comment by martbhell** [comment]
Merged into master.

**Pull request closed without merging**
